name: ModularJobs
version: '1.1'
main: net.aincraft.ModularJobsBootstrap
authors: [ mintychochip ]
api-version: '1.13'
softdepend:
  - Preferences
commands:
  test:
    description: asdads
permissions:
  modularjobs.admin:
    description: Admin commands for ModularJobs
    default: op
