name: ModularJobs
version: '1.1'
main: net.aincraft.ModularJobsBootstrap
authors: [ mintychochip ]
api-version: '1.13'
depend:
  - Mint
softdepend:
  - Choco
commands:
  test:
    description: asdads
permissions:
  modularjobs.admin:
    description: Admin commands for ModularJobs
    default: op
